# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32API-Registry
version:      0.25
version_from: Registry.pm
installdirs:  site
requires:
no_index:     ExtUtils

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
