---
name: Win32API-Registry
version: 0.31
author:
  - 'Tye McQueen, tye@metronet.com, http://www.metronet.com/~tye/.'
abstract: Low-level access to Win32 system API calls from WINREG.H
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.005
provides:
  ExtUtils::Myconst2perl:
    file: lib/ExtUtils/Myconst2perl.pm
    version: 1
  Win32API::Registry:
    file: lib/Win32API/Registry.pm
    version: 0.31
generated_by: Module::Build version 0.280802
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
