--- #YAML:1.0
name:                Win32API-Registry
version:             0.28
abstract:            Low-level access to Win32 system API calls from WINREG.H
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Tye McQueen <tye@metronet.com>
no_index:
    directory:
        - ExtUtils
