--- #YAML:1.0
name:                Win32API-Registry
version:             0.27
abstract:            Low-level access to Win32 system API calls from WINREG.H
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Tye McQueen <tye@metronet.com>
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
no_index:
    dir:
        - ExtUtils
